apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-cluster
  namespace: default
spec:
  version: '8.17.2'
  # Enable HTTP TLS with a self-signed certificate (ECK will generate certs).
  http:
    tls:
      selfSignedCertificate: {}
  nodeSets:
    - name: default
      count: 1
      config:
        node.master: true
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 1Gi
                  cpu: '20m'
                limits:
                  memory: 1Gi
                  cpu: '20m'
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ['ReadWriteOnce']
            resources:
              requests:
                storage: 1Gi
